name: Code Analysis resuable workflow

on:
 push:
   branches:
    - code-analysis-setup


jobs:
  code_analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
     
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      
      