name: Code Analysis resuable workflow

on:
 workflow_call:
    secrets:
       SONAR_TOKEN:
         required: true

  

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      